from nu_pyhepmc import NuHepMC
from validation_plots import Compare


if __name__ == '__main__':
    neut6 = NuHepMC(filename="../neut6_test/neut.6.sf.100k.hepmc3", test=False)
    neut6.get_variables("neutrinos", "leptons")

    neut5 = NuHepMC(filename="../neut5_test/neutvect.hepmc3", neut5=True, test=False)
    neut5.get_variables("neutrinos", "leptons")

    validate = Compare(neut5, neut6)
    validate.split_distro_and_ratio("interaction_mode", show=False, split="flavors")
    validate.split_distro_and_ratio("neutrino_energy", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("neutrino_energy", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("lepton_energy", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("lepton_energy", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("energy_transfer", show=False, split="flavors")
    validate.split_distro_and_ratio("energy_transfer", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("energy_transfer", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("neutrino_px", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("neutrino_py", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("neutrino_pz", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("lepton_px", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("lepton_py", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("lepton_pz", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("neutrino_px", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("neutrino_py", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("neutrino_pz", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("lepton_px", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("lepton_py", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("lepton_pz", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("lepton_momentum", show=False, split="flavors")
    validate.split_distro_and_ratio("lepton_momentum", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("momentum_transfer", show=False, split="CC-interactions")
    validate.split_distro_and_ratio("lepton_momentum", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("momentum_transfer", show=False, split="NC-interactions")
    validate.split_distro_and_ratio("momentum_transfer", show=False, split="flavors")
    validate.split_distro_and_ratio("cos_theta", show=False, split="flavors")
    validate.stacked_distro_and_ratio("cos_theta", show=False, split="CC-interactions")
    validate.stacked_distro_and_ratio("cos_theta", show=False, split="NC-interactions")
    #validate.separated_distro_and_ratio("cos_theta", show=True, split="interactions")
    # validate.stacked_distro_and_ratio(
    #     "neutrino_energy", show=True, split="interactions")
    # validate.split_distro_and_ratio("neutrino_energy", show=True)
